pearl:
  ui:
    ingress:
      enabled: true
      hosts:
        - host: pearl.dev.insee.io
          paths:
            - path: /
      tls:
        - hosts:
          - pearl.dev.insee.io

  api:
    ingress:
      enabled: true
      hosts:
        - host: pearl-api.dev.insee.io
          paths:
            - path: /
      tls:
        - hosts:
          - pearl-api.dev.insee.io

  postgresql:
    enable: true
