{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stromae.api.fullname" . }}
  labels:
    {{- include "stromae.api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "stromae.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/api/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "stromae.api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stromae.api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          {{- if .Values.postgresql.enabled }}
          env:
            - name: FR_INSEE_QUEEN_PERSISTENCE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "stromae.postgresql.fullname" .}}
                  key: password
            - name: FR_INSEE_QUEEN_PERSISTENCE_DATABASE_HOST
              value: {{  .Values.postgresql.fullnameOverride | quote }}
            - name: FR_INSEE_QUEEN_PERSISTENCE_DATABASE_USER
              value: {{  .Values.postgresql.auth.username | quote }}
            - name: FR_INSEE_QUEEN_PERSISTENCE_DATABASE_SCHEMA
              value: {{  .Values.postgresql.auth.database | quote }}
            - name: FR_INSEE_QUEEN_PERSISTENCE_DATABASE_PORT
              value: {{  .Values.postgresql.service.port | quote }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "stromae.api.fullname" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/healthcheck
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/healthcheck
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
