apiVersion: v2
name: stromae
description: A Helm chart for Kubernetes

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: 11.1.26
    repository: https://charts.bitnami.com/bitnami

type: application
version: 0.1.0
appVersion: "1.16.0"
