sonor:
  image:
    repository: inseefr/sonor
    tag: "0.5.8"
  ingress:
    enabled: true
    hosts:
      - host: sonor-host.dev.insee.io
        paths:
          - path: /
  tls:
    - hosts:
        - sonor-tls.dev.insee.io
  env:
    PEARL_JAM_URL: https://pearl-api.dev.insee.io
    QUEEN_URL_BACK_END: https://api-queen-demo.dev.insee.io
    QUEEN_URL_FRONT_END: https://queen-demo.dev.insee.io
    AUTHENTICATION_MODE: anonymous